
# updated according to workflow 
name: Run Jest Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure compatible Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Fix Permissions
        run: chmod +x customJestReporter.js

      - name: Run Tests
        run: npx jest --reporters=default --reporters=./customJestReporter.js
